# Generated by Django 5.1 on 2024-11-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_remove_post_categories_post_categories'),
        ('users', '0002_profile_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookmarked',
            field=models.ManyToManyField(blank=True, related_name='saved_blog', to='blog_app.post'),
        ),
    ]
