# Generated by Django 5.1 on 2024-11-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_bookmarked'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookmark_count',
            field=models.IntegerField(default=0),
        ),
    ]
