# Generated by Django 5.1 on 2024-11-07 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_bookmark_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bookmark_count',
        ),
    ]
